export const USER_LOGIN = 'USER_LOGIN';

export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_STUDENT_PERSONAL_INFO = 'GET_STUDENT_PERSONAL_INFO';

export const GET_ALL_EDUCATION = 'GET_ALL_EDUCATION';

export const SET_STUDENT_AS_USER = 'SET_STUDENT_AS_USER';

export const GET_STUDENT_LIST = 'GET_STUDENT_LIST';

export const GET_EDUCATION_BY_USER = 'GET_EDUCATION_BY_USER';

export const GET_ALL_COMPETENCY = 'GET_ALL_COMPETENCY';

export const GET_ACHIEVEMENT_BY_USER = 'GET_ACHIEVEMENT_BY_USER';

export const GET_All_ORAGNIZATION = 'GET_All_ORAGNIZATION';

export const GET_RECOMMENDATION_BY_USER = 'GET_RECOMMENDATION_BY_USER';

export const UPDATE_STUDENT_INFO = 'UPDATE_STUDENT_INFO';

export const GET_HEADER_COUNT = 'GET_HEADER_COUNT';

export const UPDATE_HEADER_COUNT = 'UPDATE_HEADER_COUNT';

export const CHANGE_PASSWORD_STATUS = 'CHANGE_PASSWORD_STATUS';

export const REMOVE_STUDENT_DATA = 'REMOVE_STUDENT_DATA';

export const UPDATE_USER_PERSONAL_INFO = 'UPDATE_USER_PERSONAL_INFO';

export const UPDATE_PARENT_PERSONAL_INFO = 'UPDATE_PARENT_PERSONAL_INFO';

export const GET_ACHIEVEMENT_DATA = 'GET_ACHIEVEMENT_DATA';

export const UPDATE_FEED_GROUP_INFO = 'UPDATE_FEED_GROUP_INFO';

export const GROUP_LIST_DATA = 'GROUP_LIST_DATA';
